apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  # namespace: cpu-example
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "1" # que es igual a "1000m" (milicor)
      requests:
        cpu: "0.5" # que es igual a "500m"
    args:
    - -cpus
    - "2"  # se pide mas cpu del límite, pero el pod no se reinicia ni se elimina, solamente se le va a asignar hasta su límite.