apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod
---
apiVersion: v1
kind: LimitRange
metadata:
  name: min-max
  namespace: prod
spec:
  limits: # aplica a todos los containers creados en el namespace especificado
  - max:
      memory: 1Gi
      cpu: 1
    min:
      memory: 100Mi
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
  namespace: prod
  labels:
    app: backend
    env: dev  
spec:
  containers:
  - name: cont1
    image: nginx:alpine
    resources:
      limits:
        # memory: 500M -> Ok, no supera el LimitRange definido arriba
        # memory: 2Gi # Err, over limit
        memory: 50M # Err, under limit
        # cpu: 0.5 -> Ok, no supera el valor definido
        # cpu: 2 # Err
        cpu: 50m # Err
      requests:
        memory: 50M
        cpu: 50m